"""New Attribute

Revision ID: 372ce1a34153
Revises: 2957eb8b256e
Create Date: 2025-03-27 07:02:38.087351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '372ce1a34153'
down_revision = '2957eb8b256e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('placed_students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('placed_students', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
