"""Initial migration

Revision ID: 3cb801d01644
Revises: 52e43a57438a
Create Date: 2025-03-15 17:56:11.915216

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3cb801d01644'
down_revision = '52e43a57438a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_acadamic_details')
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('last_name', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('batch', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('specialization', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('degree', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('skills', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('current_gpa', sa.Float(precision=10, asdecimal=2), nullable=True))
        batch_op.add_column(sa.Column('resume_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('backlogs', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('certificate_urls', sa.Text(), nullable=True))
        batch_op.drop_column('student_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('student_name', mysql.VARCHAR(length=255), nullable=False))
        batch_op.drop_column('certificate_urls')
        batch_op.drop_column('backlogs')
        batch_op.drop_column('resume_url')
        batch_op.drop_column('current_gpa')
        batch_op.drop_column('skills')
        batch_op.drop_column('degree')
        batch_op.drop_column('specialization')
        batch_op.drop_column('batch')
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    op.create_table('student_acadamic_details',
    sa.Column('registered_id', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('student_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('first_name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('last_name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('batch', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('specialization', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('degree', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('skills', mysql.TEXT(), nullable=True),
    sa.Column('current_gpa', mysql.FLOAT(), nullable=True),
    sa.Column('resume_url', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('backlogs', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('certificate_urls', mysql.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['student.student_id'], name='student_acadamic_details_ibfk_1'),
    sa.PrimaryKeyConstraint('registered_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
