"""Second migration

Revision ID: c02ed2496274
Revises: 6a4352647759
Create Date: 2025-03-16 16:40:12.847919

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c02ed2496274'
down_revision = '6a4352647759'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('placed_students', schema=None) as batch_op:
        batch_op.drop_column('placement_status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('placed_students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('placement_status', mysql.VARCHAR(length=255), nullable=True))

    # ### end Alembic commands ###
