"""Initial migration

Revision ID: d919e25e4116
Revises: 3cb801d01644
Create Date: 2025-03-16 13:01:16.938233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd919e25e4116'
down_revision = '3cb801d01644'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_of_interview', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_column('date_of_interview')

    # ### end Alembic commands ###
