"""Initial migration

Revision ID: fdb66a62fe20
Revises: c02ed2496274
Create Date: 2025-03-17 11:42:31.135519

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fdb66a62fe20'
down_revision = 'c02ed2496274'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.alter_column('contact_no',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=10),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.alter_column('contact_no',
               existing_type=sa.String(length=10),
               type_=mysql.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
